source/accounts/urls.py
from django.urls import path
from accounts.views import register_view, UserDetailView, \
    UserChangeView, UserChangePasswordView, UserListView
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', register_view, name='register'),
    path('profile/<pk>/', UserDetailView.as_view(), name='user_detail'),
    path('profile/<pk>/edit/', UserChangeView.as_view(), name='user_update'),
    path('profile/<pk>/change-password/', UserChangePasswordView.as_view(), name='user_change_password'),
    path('list/', UserListView.as_view(), name='user_list'),
]


app_name = 'accounts'

source/api/urls.py
from django.urls import include, path
from rest_framework import routers
from api import views

router = routers.DefaultRouter()
router.register(r'tasks', views.TaskViewSet)
router.register(r'projects', views.ProjectViewSet)

app_name = 'api'


urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))

]

source/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('api/v1/', include('api.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('webapp.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/accounts/models.py
from django.db import models
from django.contrib.auth.models import User



class Profile(models.Model):
    user = models.OneToOneField(User, related_name='profile', on_delete=models.CASCADE,
                                verbose_name='Пользователь')
    birth_date = models.DateField(null=True, blank=True, verbose_name='Дата рождения')
    avatar = models.ImageField(null=True, blank=True, upload_to='user_pics', verbose_name='Аватар')
    text = models.TextField(max_length=3000, null=True, blank=True, verbose_name='О себе')
    github_profile = models.URLField(null=True, blank=False, verbose_name='Профиль на GitHub')

    def __str__(self):
        return self.user.get_full_name() + "'s Profile"

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'

source/accounts/forms.py
from django.contrib.auth.models import User
from django import forms
from django.core.exceptions import ValidationError
from accounts.models import Profile

class UserCreationForm(forms.Form):
    username = forms.CharField(max_length=100, required=True, label='Username')
    first_name = forms.CharField(max_length=100, required=False, label='First name')
    last_name = forms.CharField(max_length=100, required=False, label='Last name')
    password = forms.CharField(max_length=100, required=True, label='Password', widget=forms.PasswordInput)
    password_confirm = forms.CharField(max_length=100, required=True, label='Password confirm',
                                       widget=forms.PasswordInput)
    email = forms.EmailField(required=True, label='Email')

    def clean(self):
        super().clean()
        password_1 = self.cleaned_data['password']
        password_2 = self.cleaned_data['password_confirm']
        first_name = self.cleaned_data['first_name']
        last_name = self.cleaned_data['last_name']
        if password_1 != password_2:
            raise ValidationError('Passwords do not match',
                                  code='passwords_do_not_match')
        if not first_name and  not last_name:
            raise ValidationError('Please fill in one of this fields: first name, last name',
                                  code='empty field')
        return self.cleaned_data

    def clean_email(self):
        email = self.cleaned_data.get('email')
        try:
            User.objects.get(email=email)
            raise ValidationError('User with this email already exists',
                                  code='user_email_exists')
        except User.DoesNotExist:
            return email

    def clean_username(self):
        username = self.cleaned_data.get('username')
        try:
            User.objects.get(username=username)
            raise ValidationError('User with this username already exists',
                                  code='user_username_exists')
        except User.DoesNotExist:
            return username






class UserChangeForm(forms.ModelForm):
    avatar = forms.ImageField(label='Аватар', required=False)
    birth_date = forms.DateField(label='День рождения', input_formats=['%Y-%m-%d', '%d.%m.%Y'], required=False)
    text = forms.CharField(max_length=3000, label='О себе', required=False, widget=forms.Textarea)
    github_profile = forms.URLField(label='Профиль на GitHub', required=False)


    def get_initial_for_field(self, field, field_name):
        if field_name in self.Meta.profile_fields:
            return getattr(self.instance.profile, field_name)
        return super().get_initial_for_field(field, field_name)

    def save(self, commit=True):
        user = super().save(commit)
        self.save_profile(commit)
        return user

    def save_profile(self, commit=True):
        profile = self.instance.profile
        for field in self.Meta.profile_fields:
            setattr(profile, field, self.cleaned_data[field])

        if not profile.avatar:
            profile.avatar = None

        if commit:
            profile.save()

    def clean_github_profile(self):
        github_profile = self.cleaned_data.get('github_profile')
        if not github_profile.startswith('https://github.com/') and github_profile is not '':
            raise ValidationError('profile address is incorrect', code='wrong address')
        return github_profile

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'text', 'avatar', 'github_profile']
        profile_fields = ['avatar', 'birth_date', 'github_profile', 'text']
        labels = {'first_name': 'Имя', 'last_name': 'Фамилия', 'email': 'Email'}




class UserChangePasswordForm(forms.ModelForm):
    password = forms.CharField(max_length=100, required=True, label='New Password',
                               widget=forms.PasswordInput)
    password_confirm = forms.CharField(max_length=100, required=True, label='New Password confirm',
                                       widget=forms.PasswordInput)
    old_password = forms.CharField(max_length=100, required=True, label='Old Password',
                                        widget=forms.PasswordInput)

    def clean_old_password(self):
        old_password = self.cleaned_data.get('old_password')
        user = self.instance
        if not user.check_password(old_password):
            raise ValidationError('Invalid password ', code='invalid_password')
        return old_password

    def clean(self):
        super().clean()
        password_1 = self.cleaned_data['password']
        password_2 = self.cleaned_data['password_confirm']
        if password_1 != password_2:
            raise ValidationError('New Passwords do not match',
                                  code='passwords_do_not_match')
        return self.cleaned_data

    def save(self, commit=True):
        user = self.instance
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = ['password', 'password_confirm', 'old_password']

source/accounts/views.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.urls import reverse
from django.views.generic import DetailView, UpdateView, ListView
from accounts.forms import UserCreationForm, UserChangeForm, UserChangePasswordForm
from accounts.models import Profile


def register_view(request):
    if request.method == 'GET':
        form = UserCreationForm()
        return render(request, 'register.html', {'form': form})
    elif request.method == 'POST':
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            user = User(
                username=form.cleaned_data['username'],
                first_name= form.cleaned_data['first_name'],
                last_name = form.cleaned_data['last_name'],
                email=form.cleaned_data['email']
            )
            user.set_password(form.cleaned_data['password'])
            user.save()
            Profile.objects.create(user=user)
            login(request, user)
            return redirect('webapp:index')
        else:
            return render(request, 'register.html', {'form': form})


class UserDetailView(DetailView):
    model = User
    template_name = 'user_detail.html'
    context_object_name = 'user_obj'


class UserChangeView(UserPassesTestMixin, UpdateView):
    model = User
    template_name = 'user_update.html'
    form_class = UserChangeForm
    context_object_name = 'user_obj'

    def test_func(self):
        return self.get_object() == self.request.user

    def get_success_url(self):
        return reverse('accounts:user_detail', kwargs={'pk': self.object.pk})


class UserChangePasswordView(UserPassesTestMixin, UpdateView):
    model = User
    template_name = 'user_password_change.html'
    form_class = UserChangePasswordForm
    context_object_name = 'user_obj'

    def test_func(self):
        return self.get_object() == self.request.user

    def get_success_url(self):
        return reverse('accounts:user_detail', kwargs={'pk': self.object.pk})




class UserListView(ListView):
    template_name = 'user_list.html'
    model = User
    context_object_name = 'user_obj'

source/accounts/templates/register.html
{% extends 'base.html' %}

{% block content %}
    <h1>Sing Up</h1>
    <form action="{% url 'accounts:register' %}" method="post">
    {% include 'partial/form.html' with button_text='Сохранить'%}
    </form>
{% endblock %}

source/accounts/templates/user_detail.html
{% extends 'base.html' %}
{% block title %}{{ user_obj.username }}{% endblock %}
{% block menu %}
    {% if user_obj == request.user %}
        <li><a href="{% url 'accounts:user_update' user_obj.pk %}">Edit Profile</a></li>
        <li><a href="{% url 'accounts:user_change_password' user_obj.pk %}">Change Password</a></li>
    {% endif %}
{% endblock %}
{% block content %}
   {% if user_obj.profile.avatar %}
       <img class="avatar" src="{{ user_obj.profile.avatar.url }}" width="250" height="250" alt="user picture">
   {% else %}
       <p><img class="avatar" src="http://vovet.ru/uploads/img/87/2d2008efd304884c51cf7c6825e12bb8-650.jpg"></p>
   {% endif %}
    <h1>Profile: {{ user_obj.username }}</h1>
    <p>First Name: {{ user_obj.first_name }}</p>
    <p>Last Name: {{ user_obj.last_name }}</p>
    <p>Дата рождения: {{ user_obj.profile.birth_date|date:'d.m.Y' }}</p>
    <p>Email: {{ user_obj.email }}</p>
    <p>About me:{{ user_obj.profile.about_me }}</p> <br>
    <p>GitHub profile:{{ user_obj.profile.github_profile }}</p>
{% endblock %}

source/accounts/templates/user_list.html
{% extends 'base.html' %}

{% block title %}
    {{ user_obj.username }}
{% endblock %}

{% block content %}
    {% for user in user_obj %}
    <p>Name User: {{ user.username }}</p>
    <li><a href="{% url 'accounts:user_detail' user.pk %}">User Profile</a></li>
    <br>
    {% endfor %}

{% endblock%}

source/accounts/templates/user_password_change.html
{% extends 'base.html' %}

{% block title %}
    {{ user_obj.username }}
{% endblock %}

{% block menu %}
    {% if user_obj == request.user %}
        <li><a href="{% url 'accounts:user_detail' user_obj.pk %}">View</a></li>
        <li><a href="{% url 'accounts:user_update' user_obj.pk %}">Edit Profile</a></li>
    {% endif %}
{% endblock %}

{% block content %}
    <h1>Change Password: {{ user_obj.username }}</h1>
    <form action="{% url 'accounts:user_change_password' user_obj.pk %}" method="post">
    {% include 'partial/form.html' with button_text='Save' %}
    </form>
{% endblock %}

source/accounts/templates/user_update.html
{% extends 'base.html' %}

{% block title %}
    {{ user_obj.username }}
{% endblock %}

{% block menu %}
    {% if user_obj == request.user %}
        <li><a href="{% url 'accounts:user_detail' user_obj.pk %}">View</a></li>
        <li><a href="{% url 'accounts:user_change_password' user_obj.pk %}">Change Password</a></li>
    {% endif %}
{% endblock %}

{% block content %}
    <h1>Edit Profile: {{ user_obj.username }}</h1>
    <form action="{% url 'accounts:user_update' user_obj.pk %}" method="post" enctype="multipart/form-data">
    {% include 'partial/form.html' with button_text='Update' %}
    </form>
{% endblock %}