source/api/urls.py
from django.urls import include, path
from rest_framework import routers
from api import views

router = routers.DefaultRouter()
router.register(r'tasks', views.TaskViewSet)
router.register(r'projects', views.ProjectViewSet)

app_name = 'api'


urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))

]

source/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('api/v1/', include('api.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('webapp.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from webapp.views import IndexView, TaskView, TaskCreateView, TaskUpdateView, TaskDeleteView, StatusIndexView, \
    StatusCreateView, StatusUpdateView, StatusDeleteView, TypeIndexView, TypeCreateView, TypeUpdateView, TypeDeleteView
from webapp.views.project_views import ProjectIndexView, ProjectView, ProjectCreateView, ProjectUpdateView, \
    ProjectDeleteView


app_name = 'webapp'


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('task/<int:pk>', TaskView.as_view(), name='task_view'),
    path('task/create/', TaskCreateView.as_view(), name='task_create'),
    path('task/<int:pk>/edit/', TaskUpdateView.as_view(), name='task_update'),
    path('task/<int:pk>/delete/', TaskDeleteView.as_view(), name='task_delete'),
    path('status/', StatusIndexView.as_view(), name='status_index'),
    path('status/create/', StatusCreateView.as_view(), name='status_create'),
    path('status/<int:pk>/edit/', StatusUpdateView.as_view(), name='status_update'),
    path('status/<int:pk>/delete', StatusDeleteView.as_view(), name='status_delete'),
    path('type/', TypeIndexView.as_view(), name='type_index'),
    path('type/create/', TypeCreateView.as_view(), name='type_create'),
    path('type/<int:pk>/edit/', TypeUpdateView.as_view(), name='type_update'),
    path('type/<int:pk>/delete', TypeDeleteView.as_view(), name='type_delete'),
    path('project/', ProjectIndexView.as_view(), name='project_index'),
    path('project/<int:pk>', ProjectView.as_view(), name='project_view'),
    path('project/create/', ProjectCreateView.as_view(), name='project_create'),
    path('project/<int:pk>/edit/', ProjectUpdateView.as_view(), name='project_update'),
    path('project/<int:pk>/delete', ProjectDeleteView.as_view(), name='project_delete'),

]

source/webapp/models.py
from django.db import models


class Task(models.Model):
    summary = models.CharField(max_length=200, null=False, blank=False, verbose_name='Заголовок')
    description = models.TextField(max_length=3000, null=True, blank=True, verbose_name='Текст')
    status = models.ForeignKey('webapp.Status', on_delete=models.PROTECT, null=True, blank=True, verbose_name='Статус',
                               related_name='statuses')
    type = models.ForeignKey('webapp.Type', on_delete=models.PROTECT, null=True, blank=True, verbose_name='Тип',
                             related_name='types')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    project = models.ForeignKey('webapp.Project', null=True, blank=False, related_name='projects',
                                on_delete=models.PROTECT, verbose_name='Проект')

    def __str__(self):
        return "{}. {}".format(self.pk, self.summary)



class Status(models.Model):
    name = models.CharField(max_length=20, verbose_name='Название')

    def __str__(self):
        return self.name


class Type(models.Model):
    name = models.CharField(max_length=20, verbose_name='Название')

    def __str__(self):
        return self.name




class Project(models.Model):
    name = models.CharField(max_length=200, verbose_name='Название проекта')
    description = models.TextField(max_length=400, null=True, blank=True, verbose_name='Описание')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Время изменения')

    def __str__(self):
        return self.name

source/webapp/forms.py
from django import forms
from webapp.models import Status, Type, Task, Project


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        exclude = []


class StatusForm(forms.ModelForm):
    class Meta:
        model = Status
        exclude = []


class TypeForm(forms.ModelForm):
    class Meta:
        model = Type
        exclude = []


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        exclude = []


class SimpleSearchForm(forms.Form):
    search = forms.CharField(max_length=100, required=False, label="Найти")

source/webapp/views/project_views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from django.utils.http import urlencode
from django.views.generic import ListView, TemplateView, CreateView, UpdateView, DeleteView
from webapp.forms import ProjectForm, SimpleSearchForm
from webapp.models import Project


class ProjectIndexView(ListView):
    template_name = 'project/index.html'
    model = Project
    context_object_name = 'projects'

    # def get_queryset(self):
    #     return Project.objects.all().order_by('created_at')


    def get(self, request, *args, **kwargs):
        form = SimpleSearchForm(self.request.GET)
        query = None
        if form.is_valid():
            query = form.cleaned_data['search']
        self.form = form
        self.query = query
        return super().get(request, *args, **kwargs)


    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        if self.query:
            context['query'] = urlencode({'search': self.query})
        context['form'] = self.form
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.query:
            queryset = queryset.filter(Q(name__icontains=self.query))
        return queryset


class ProjectView(TemplateView):
    template_name = 'project/project.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        project_pk = kwargs.get('pk')
        context['project'] = get_object_or_404(Project, pk=project_pk)
        return context



class ProjectCreateView(LoginRequiredMixin, CreateView):
    template_name = 'project/create.html'
    form_class = ProjectForm
    model = Project

    def get_success_url(self):
        return reverse('webapp:project_view', kwargs={'pk': self.object.pk})



class ProjectUpdateView(LoginRequiredMixin, UpdateView):
    model = Project
    template_name = 'project/update.html'
    form_class = ProjectForm
    context_object_name = 'project'

    def get_success_url(self):
        return reverse('webapp:project_view', kwargs={'pk': self.object.pk})



class ProjectDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'project/delete.html'
    model = Project
    context_key = 'project'
    success_url = reverse_lazy('webapp:project_index')

source/webapp/views/status_views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from webapp.forms import StatusForm
from webapp.models import Status




class StatusIndexView(ListView):
    template_name = 'status/status_index.html'
    model = Status
    context_object_name = 'statuses'



class StatusCreateView(LoginRequiredMixin, CreateView):
    template_name = 'status/status_create.html'
    form_class = StatusForm
    model = Status

    def get_success_url(self):
        return reverse('webapp:status_index')




class StatusUpdateView(LoginRequiredMixin, UpdateView):
    model = Status
    template_name = 'status/status_update.html'
    form_class = StatusForm
    context_object_name = 'status'

    def get_success_url(self):
        return reverse('webapp:status_index')




class StatusDeleteView(LoginRequiredMixin, DeleteView):
    model = Status
    template_name = 'status/status_delete.html'
    form_class = StatusForm
    context_object_name = 'status'

    def get_success_url(self):
        return reverse('webapp:status_index')

source/webapp/views/task_views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from django.utils.http import urlencode
from django.views.generic import TemplateView, ListView, CreateView, UpdateView, DeleteView
from webapp.forms import TaskForm, SimpleSearchForm
from webapp.models import Task



class IndexView(ListView):
    template_name = 'task/index.html'
    model = Task
    context_object_name = 'tasks'
    paginate_by = 2
    paginate_orphans = 1

    def get(self, request, *args, **kwargs):
        form = SimpleSearchForm(self.request.GET)
        query = None
        if form.is_valid():
            query = form.cleaned_data['search']
        self.form = form
        self.query = query
        return super().get(request, *args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        if self.query:
            context['query'] = urlencode({'search': self.query})
        context['form'] = self.form
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.query:
            queryset = queryset.filter(Q(summary__icontains=self.query) | Q(description__icontains=self.query))
        return queryset



class TaskView(TemplateView):
    template_name = 'task/task.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        task_pk = kwargs.get('pk')
        context['task'] = get_object_or_404(Task, pk=task_pk)
        return context




class TaskCreateView(LoginRequiredMixin, CreateView):
    template_name = 'task/create.html'
    form_class = TaskForm
    model = Task

    def get_success_url(self):
        return reverse('webapp:task_view', kwargs={'pk': self.object.pk})




class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    template_name = 'task/update.html'
    form_class = TaskForm
    context_object_name = 'task'

    def get_success_url(self):
        return reverse('webapp:task_view', kwargs={'pk': self.object.pk})



class TaskDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'task/delete.html'
    model = Task
    context_key = 'task'
    success_url = reverse_lazy('webapp:index')

source/webapp/views/type_views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from webapp.forms import TypeForm
from webapp.models import Type




class TypeIndexView(ListView):
    template_name = 'type/index.html'
    model = Type
    context_object_name = 'types'



class TypeCreateView(LoginRequiredMixin, CreateView):
    template_name = 'type/create.html'
    form_class = TypeForm
    model = Type

    def get_success_url(self):
        return reverse('webapp:type_index')




class TypeUpdateView(LoginRequiredMixin, UpdateView):
    model = Type
    template_name = 'type/update.html'
    form_class = TypeForm
    context_object_name = 'type'

    def get_success_url(self):
        return reverse('webapp:type_index')




class TypeDeleteView(LoginRequiredMixin, DeleteView):
    model = Type
    template_name = 'type/delete.html'
    form_class = TypeForm
    context_object_name = 'type'

    def get_success_url(self):
        return reverse('webapp:type_index')

source/webapp/templates/task/create.html
{% extends 'base.html' %}

    {% block title %}Create Task{% endblock %}

{% block content %}

<h1 class="crearet"> Create Article</h1>
<form method="POST" action="{% url "webapp:task_create" %}">
   {% include 'partial/form.html' with button_text='Create' %}
</form>
{% endblock %}

</body>
</html>

source/webapp/templates/task/delete.html
{% extends 'base.html' %}

    {% block title %}Delete Task{% endblock %}

{% block menu %}
    <li><a href="{% url 'webapp:task_view'  task.pk %}">View</a></li>
{% endblock %}

{% block content %}
    <form method="POST" action="{% url "webapp:task_delete" task.pk%}" class="text-center">
        <h1>Are you sure want to delete article "{{ task }}"?</h1>
        {% csrf_token %}
        <input type="submit" value="Confirm" class="btn btn-danger">
        <p><a href="{% url "webapp:index" %}" class="btn btn-primary">Cancel</a></p>
    </form>
{% endblock %}

</body>
</html>

source/webapp/templates/task/index.html
{% extends 'base.html' %}

{% block menu %}
    <li><a href="{% url 'webapp:task_create' %}">Add Task</a></li>
{% endblock %}

{% block content %}

    <li><a href="{% url 'webapp:status_index' %}">Statuses</a></li>
    <li><a href="{% url 'webapp:type_index' %}">Types</a></li>
    <li><a href="{% url 'webapp:project_index' %}">Projects</a></li>



    <h1 style="text-align: center">Task</h1>
        {% include 'partial/simple_search.html' %}

{% if is_paginated %}
   {% include 'partial/pagination.html' %}
{% endif %}



    {% for task in tasks %}
        <div class="text-center">
            <h2>Заголовок: {{ task.summary }}</h2>
            <p>Текст: {{ task.description }}</p>
            <p>Статус: {{ task.status }}</p>
            <p>Тип: {{ task.type }}</p>
            <p>created_at: {{ task.created_at }}</p>
            <p>
                <a href="{% url 'webapp:task_view' task.pk %}">More...</a>
                <a href="{% url 'webapp:task_update' task.pk %}">Edit</a>
                <a href="{% url 'webapp:task_delete' task.pk %}">Delete</a>
            </p>
            </p>
            <hr>
        </div>
    {% endfor %}

{#{% if is_paginated %}#}
{#   {% include 'partial/pagination.html' %}#}
{#{% endif %}#}

{% endblock%}

source/webapp/templates/task/task.html
{% extends 'base.html' %}

{#{% block title %}{{ task.summary }}{% endblock %}#}

{% block menu %}
    <li><a href="{% url 'webapp:task_view'  task.pk %}">Edit</a></li>
     <li><a href="{% url 'webapp:task_delete' task.pk %}">Delete</a></li>

{% endblock %}

{% block content %}
    <h1 class="crearet">Заголовок: {{ task.summary  }}</h1>
    <p>Статус: {{ task.status }}<p>
    <p>Тип: {{ task.type| default_if_none:'Без категорий' }}
    <p>created_at: {{ task.created_at|date:'d.n.Y H:i:s' }}</p>
    <div class="pre">Текст: {{ task.description }}</div>
{% endblock %}

source/webapp/templates/task/update.html
{% extends 'base.html' %}

    {% block title %}Update Task{% endblock %}

{% block menu %}
    <li><a href="{% url 'webapp:task_view'  task.pk %}">View</a></li>
{% endblock %}

{% block content %}
<h1 class="crearet"> Update Task</h1>
<form method="POST" action="{% url "webapp:task_update" task.pk%}">
   {% include 'partial/form.html' with button_text='Update'%}
</form>
{% endblock %}